[local]
localhost ansible_connection=local ansible_user=akim ansible_become_password=Zadi@k_1997

[vpn-servers]
#vpn-server ansible_host=192.168.5.21 ansible_user=akim ansible_password=Zadi@k_1997 ansible_become_password=Zadi@k_1997
vpn-server ansible_host=192.168.5.21 ansible_user=akim ansible_become_password=Zadi@k_1997

[vpn-client]
#vpn-client ansible_host=192.168.5.22 ansible_user=akim ansible_password=Zadi@k_1997 ansible_become_password=Zadi@k_1997
vpn-client ansible_host=192.168.5.22 ansible_user=akim
